name: Linux Build

on:
  push:
    branches: []
  pull_request:
    branches: []

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    strategy:
     matrix:
       compiler: [gcc, clang]
       include:
        - compiler: gcc
          ccompiler: gcc
          cxxcompiler: g++
        - compiler: clang
          ccompiler: clang
          cxxcompiler: clang++  
    steps:
    - uses: actions/checkout@v2
    - name: reps
      run : sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
    - name: update
      run: sudo apt-get update -y -qq
    - name: install gcc10
      run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10 --slave /usr/bin/gcov gcov /usr/bin/gcov-10
    - name: install clang
      run: sudo apt-get install clang
    #dependencies
    - name: install sdl2
      run: sudo apt-get install libsdl2-dev
    - name: install sdl2-image
      run: sudo apt-get install libsdl2-image-dev
    - name: install sdl2-ttf
      run: sudo apt-get install libsdl2-ttf-dev
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      env:
       C: ${{ matrix.ccompiler }}
       CXX: ${{ matrix.cxxcompiler }}
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}