# This is a basic workflow to help you get started with Actions

name: Ctests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run_test_linux_gcc10:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: reps
      run : sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
    
    
    - name: update
      run: sudo apt-get update -y -qq
    - name: install gcc10
      run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10 --slave /usr/bin/gcov gcov /usr/bin/gcov-10

    #dependencies
    - name: install sdl2
      run: sudo apt-get install libsdl2-dev
    - name: install sdl2-image
      run: sudo apt-get install libsdl2-image-dev
    - name: install sdl2-ttf
      run: sudo apt-get install libsdl2-ttf-dev
    #run tests
    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/tests -B ${{github.workspace}}/tests/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/tests/build 
    - name: Test
      run: ctest --test-dir tests/build
  job:
    name: ${{matrix.os}}-vcpkg
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: lukka/run-vcpkg@v10
      with:
        vcpkgGitCommitId: '5568f110b509a9fd90711978a7cb76bae75bb092'
        cmakeListsTxtPath: '${{ github.workspace }}/tests/CMakeLists.txt'
    - name: build
      uses: lukka/run-cmake@v10
      with:
          configurePreset: 'ninja-multi-vcpkg-clang'
          buildPreset: 'ninja-multi-vcpkg-clang'
  
    
    
